# Generated by Django 3.0.2 on 2020-01-28 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0002_activitytype_direction_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start', models.TextField()),
                ('end', models.TextField()),
                ('height', models.TextField()),
                ('startHour', models.IntegerField()),
                ('startMinute', models.IntegerField()),
                ('endHour', models.IntegerField()),
                ('endMinute', models.IntegerField()),
                ('activityDate', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplace.Direction')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplace.Project')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workplace.ActivityType')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность',
                'verbose_name_plural': 'Активность',
            },
        ),
    ]
