# Generated by Django 3.0.2 on 2020-01-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endHour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='endMinute',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='height',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startHour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startMinute',
            field=models.IntegerField(null=True),
        ),
    ]
