# Generated by Django 3.0.3 on 2020-02-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workplace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0005_activity_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'xls'), (1, 'doc'), (2, 'xls'), (3, 'doc')], null=True)),
                ('state', models.IntegerField(choices=[(0, 'В процессе'), (1, 'Завершен'), (2, 'Ошибка')], default=0, null=True)),
                ('link', models.FileField(max_length=1024, null=True, upload_to=workplace.models.upload_report_path)),
                ('generated', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёт',
            },
        ),
    ]
