# Generated by Django 3.0.3 on 2020-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0008_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
