# Generated by Django 3.0.3 on 2020-03-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0009_user_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '[ActivityTimer] Таймер активности',
                'verbose_name_plural': '[ActivityTimer] Таймер активности',
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '[Activity] Активность', 'verbose_name_plural': '[Activity] Активность'},
        ),
    ]
