# Generated by Django 3.0.3 on 2021-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0010_auto_20200304_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
    ]
