# Generated by Django 3.0.3 on 2021-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0014_auto_20210405_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimer',
            name='state',
            field=models.IntegerField(choices=[(1, 'В процессе'), (2, 'Завершен')], default=1, null=True),
        ),
    ]
