# Generated by Django 3.0.3 on 2021-04-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0015_auto_20210405_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimer',
            name='completed',
            field=models.DateField(null=True),
        ),
    ]
