# Generated by Django 3.0.3 on 2021-04-06 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0016_auto_20210405_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytimer',
            name='activityDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitytimer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
