# Generated by Django 3.0.3 on 2021-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0017_auto_20210406_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytimer',
            name='state',
            field=models.IntegerField(choices=[(1, 'В процессе'), (2, 'Завершен'), (3, 'Прерван')], default=1, null=True),
        ),
    ]
