# Generated by Django 3.0.3 on 2021-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0018_auto_20210406_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='direction',
        ),
        migrations.AddField(
            model_name='activitytype',
            name='direction',
            field=models.ManyToManyField(blank=True, default=[], related_name='activity_types', to='workplace.Direction'),
        ),
    ]
